default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: journey_route_development

test:
  <<: *default
  database: journey_route_test

production:
  <<: *default
  database: journey_route_production
  username: journey_route
  password: <%= ENV["JOURNEY_ROUTE_DATABASE_PASSWORD"] %>
